---
version: '2'
services:
  this-image:
    restart: 'no'
    build:
      context: ./
      args:
        KUBECTL_VER: ${KUBECTL_VER}
    image: ${DOCKER_ID}/${NAME}:${KUBECTL_VER}
    # for test
    command: /bin/sh -c 'while true; do echo dummy; sleep 600; done'
