---
version: '2'
services:
  docker-image:
    restart: 'no'
    build:
      context: ./
      args:
        KUBECTL_VER: ${KUBECTL_VER}
    image: ${DOCKER_ID}/${NAME}:${KUBECTL_VER}
    #command: /bin/sh
